# Generated by Django 5.2.3 on 2025-06-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimalHealthIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("livestock_density", models.FloatField(blank=True, null=True)),
                ("livestock_ownership", models.FloatField(blank=True, null=True)),
                ("itl_coverage", models.FloatField(blank=True, null=True)),
                ("distance_to_livestock", models.FloatField(blank=True, null=True)),
                (
                    "dominant_livestock_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnvironmentalClimaticIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("rainfall", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("ndvi", models.FloatField(blank=True, null=True)),
                ("evapotranspiration", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HumanHealthIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("malaria_incidence", models.FloatField(blank=True, null=True)),
                ("test_positivity_rate", models.FloatField(blank=True, null=True)),
                ("parasite_prevalence", models.FloatField(blank=True, null=True)),
                ("anemia_prevalence", models.FloatField(blank=True, null=True)),
                ("malaria_mortality_rate", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
